import "@smastrom/react-rating/style.css";
import { Lato } from "next/font/google";
import "./globals.css";
import RootLayout from "@/components/details/RootLayout";

const lato = Lato({
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Tools 121 : Home",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased text-slate-500 bg-white`}
        suppressHydrationWarning={true}
        data-theme="main"
      >
        <div className="">
          <main>
            <RootLayout>
              {children}
            </RootLayout>
          </main>
        </div>
      </body>
    </html>
  );
}
