import "@smastrom/react-rating/style.css";
import Header from "@/components/common/Header";
import Information from "@/components/home/Information";
import Footer from "@/components/common/Footer";
import Copyright from "@/components/common/Copyright";
import { Suspense } from "react";

export const metadata = {
  title: "Tools 121 : Home",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <Header />
      {children}
      <Information />
      <Suspense fallback={<div className="container px-4 sm:px-8 pb-8 py-16 2xl:py-20 lg:px-8">Loading...</div>}>
        <Footer />
      </Suspense>
      <Copyright />
    </>
  );
}
